server:
  port: 7002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      filter:
        remove-hop-by-hop:
          headers:
            # 以下是去掉网关默认去掉的请求响应头
            - trailer
            - te
            - keep-alive
            - transfer-encoding
            - upgrade
            - proxy-authenticate
            - connection
            - proxy-authorization
            - x-application-context
            # 以下是去掉服务层面定义的跨域
            - access-control-allow-credentials
            - access-control-allow-headers
            - access-control-allow-methods
            - access-control-allow-origin
            - access-control-max-age
            - vary
      globalcors:
        corsConfigurations:
          '[/**]':                     #设置允许跨域的路径
            allowCredentials: true     #是否允许cookie
            allowedOrigins: "*"        #设置允许跨域请求的域名
            allowedHeaders: "*"        #设置允许的header属性
            allowedMethods: "*"        #设置允许的请求方式
            maxAge: 3628800            #跨域允许时间
      #配置微服务路由
      routes:
        - id: auth-center
          uri: lb://auth-center
          predicates:
            - Path=/auth-center/**
          filters:
            - StripPrefix=1
        - id: project-management
          uri: lb://project-management
          predicates:
            - Path=/project-management/**
          filters:
            - StripPrefix=1

logging:
  level:
    root: info
  file: logs/${spring.application.name}.log

ignorePaths:
  auth/login,
  projectInfo/projectDetailInfo,
  v2/api-docs,
  doc.html