
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.18:3306/project?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: iscas654321
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

auth:   #本地token
  ttl: 3600    #token存储到redis的过期时间
  clientId: pmservice
  clientSecret: pmservice

encrypt:
  key-store:
    location: classpath:/pmservice.jks   #证书认证位置   本地证书配置
    secret: pmservice                #秘钥(用于加盐)
    alias: pmservice
    password: pmservice    #证书密码

#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:7001/eureka
#    registry-fetch-interval-seconds: 5
#  instance:
#    lease-expiration-duration-in-seconds: 15
#    lease-renewal-interval-in-seconds: 5
#    prefer-ip-address: true
logging:
  level:
    com.user: debug
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}