spring:
  application:
    name: doc-generator
server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}