spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  application:
    name: project-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.77:3306/pm_primary?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: iscas654321

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  # 控制台输出sql语句
  type-enums-package: com.iscas.pm.api.model.project
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启下划线转驼峰
    map-underscore-to-camel-case: true
server:
  port: 5005

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

logging:
  level:
    root: info
  file: logs/${spring.application.name}.log

# 分布式文件系统FDFS配置
fdfs:
  connect-timeout: 600  # 连接超时时间
  so-timeout: 1500      # 读取超时时间
  tracker-list: 192.168.100.246:22122  # tracker服务配置地址列表，替换成自己服务的IP地址，支持多个
  pool:
    jmx-enabled: false
  thumb-image:
    height: 150       # 缩略图的宽高
    width: 150
