spring:
  application:
    name: auth-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.18:3306/pm_primary?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: iscas654321
  redis:
    host: 192.168.100.18
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 7004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

auth:   #本地token
  ttl: 3600  #token存储到redis的过期时间
  clientId: pmservice
  clientSecret: pmservice   #秘钥
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/pmservice.jks   #证书认证位置
    secret: pmservice
    alias: pmservice
    password: pmservice
#feign:
#  compression:
#    request:
#      enabled: false
#
#    response:
#      enabled: false
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:7001/eureka
#    registry-fetch-interval-seconds: 5
#  instance:
#    lease-expiration-duration-in-seconds: 15
#    lease-renewal-interval-in-seconds: 5
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}